spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
  jpa:
    database-platform:
    hibernate: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/todo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
